<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MechPro.J2534.Uds</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\J2534.IsoTp\J2534.IsoTp.csproj" />
  </ItemGroup>
</Project>
